### ISSUE TITLE
Cannot  compile project - webpack old

### ISSUE THREAD

**Issue by djgel** [morcibacsi/PSACANBridgeSetup#1]
Try  add Portuguese  language and add 3008 icockpit panel config.

when try 	compile get  error, webpack": "^4.41.26", and "copy-webpack-plugin": "^8.0.0", old :)

Can change this for new  docker compiler ?

	"@types/webpack": "^4.41.26",
		"@typescript-eslint/eslint-plugin": "^4.17.0",
		"@typescript-eslint/parser": "^4.17.0",
		"copy-webpack-plugin": "^8.0.0",
		"css-loader": "^5.2.7",
		"eslint": "^7.21.0",
		"eslint-config-standard-preact": "^1.1.6",
		"eslint-loader": "^4.0.2",
		"eslint-plugin-optimize-regex": "^1.2.0",
		"eslint-plugin-preact": "^0.1.0",
		"eslint-plugin-promise": "^4.3.1",
		"eslint-plugin-sonarjs": "^0.6.0",
		"file-loader": "^6.2.0",
		"less": "^4.1.1",
		"less-loader": "^8.0.0",
		"less-plugin-clean-css": "^1.5.1",
		"optimize-css-assets-webpack-plugin": "^5.0.4",
		"preact-svg-loader": "^0.2.1",
		"purgecss": "^4.0.3",
		"purgecss-webpack-plugin": "^4.0.3",
		"react-snap": "^1.13.1",
		"rimraf": "^3.0.2",
		"style-loader": "^3.2.1",
		"ts-loader": "^8.0.18",
		"typescript": "^4.2.3",
		"webpack": "^4.46.0",
		"webpack-cli": "^4.5.0",
		"webpack-dev-server": "^3.11.2"

**Comment by djgel** [comment]
[webpack-cli] TypeError: compilation.getCache is not a function
psacanbridgesetup-main-preact-boilerplate-1  |     at /app/node_modules/copy-webpack-plugin/dist/index.js:473:33
psacanbridgesetup-main-preact-boilerplate-1  |     at SyncHook.eval [as call] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
psacanbridgesetup-main-preact-boilerplate-1  |     at SyncHook.lazyCompileHook (/app/node_modules/tapable/lib/Hook.js:154:20)
psacanbridgesetup-main-preact-boilerplate-1  |     at Compiler.newCompilation (/app/node_modules/webpack/lib/Compiler.js:630:30)
psacanbridgesetup-main-preact-boilerplate-1  |     at /app/node_modules/webpack/lib/Compiler.js:667:29
psacanbridgesetup-main-preact-boilerplate-1  |     at AsyncSeriesHook.eval [as callAsync] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
psacanbridgesetup-main-preact-boilerplate-1  |     at AsyncSeriesHook.lazyCompileHook (/app/node_modules/tapable/lib/Hook.js:154:20)
psacanbridgesetup-main-preact-boilerplate-1  |     at Compiler.compile (/app/node_modules/webpack/lib/Compiler.js:662:28)
psacanbridgesetup-main-preact-boilerplate-1  |     at /app/node_modules/webpack/lib/Compiler.js:321:11
psacanbridgesetup-main-preact-boilerplate-1  |     at Compiler.readRecords (/app/node_modules/webpack/lib/Compiler.js:529:11)
psacanbridgesetup-main-preact-boilerplate-1  |     at /app/node_modules/webpack/lib/Compiler.js:318:10
psacanbridgesetup-main-preact-boilerplate-1  |     at AsyncSeriesHook.eval [as callAsync] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
psacanbridgesetup-main-preact-boilerplate-1  |     at AsyncSeriesHook.lazyCompileHook (/app/node_modules/tapable/lib/Hook.js:154:20)
psacanbridgesetup-main-preact-boilerplate-1  |     at /app/node_modules/webpack/lib/Compiler.js:315:19
psacanbridgesetup-main-preact-boilerplate-1  |     at AsyncSeriesHook.eval [as callAsync] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
psacanbridgesetup-main-preact-boilerplate-1  |     at AsyncSeriesHook.lazyCompileHook (/app/node_modules/tapable/lib/Hook.js:154:20)
psacanbridgesetup-main-preact-boilerplate-1  | npm ERR! code ELIFECYCLE

**Comment by morcibacsi** [comment]
Currently I don't have time to fiddle around with it, but if you send your modified version, I try to add it to the project, and compile it for you.

**Comment by djgel** [comment]
ok my  friend, i request!!  thanks!

**Comment by morcibacsi** [comment]
Thanks, updated this repository, and also the other one with the compiled file. I will keep this issue open, so I won't forget to update webpack.

**Comment by morcibacsi** [comment]
It should be resolved by e76abc9
If not feel free to reopen.

**Comment by djgel** [comment]
Tks  Men!!! You are the  best!

**Comment by morcibacsi** [comment]
No worries, just keep sending the pull requests, when I have some free time I am going to test and merge them.
